version: "2"

services:
  teamspeak:    
    restart: always
    build: ./teamspeak-image
    ports:
      - "10011:10011"
      - "30033:30033"
      - "9987:9987/udp"
    volumes:
      - "./v/teamspeak:/home/teamspeak:rw"
    logging:
      driver: json-file
      options:
        max-size: "100k"
        max-file: "20"
      