version: "3"

services:
  teamspeak:    
    restart: always
    build: ./ts3server-image
    ports:
      - "10011:10011"
      - "30033:30033"
      - "9987:9987/udp"
    volumes:
      - serverfiles:/home/lgsm/serverfiles
      - log:/home/lgsm/log

volumes:
  serverfiles:  
  log:
  

      

      